#!/usr/bin/env bash
export REPO_OWNER="MinecraftSeverWrapper"
export REPO="MSW-API"

# Locate newly created jar
export RELEASE_FILE=$(ls target/msw-api-*.jar)
echo Releasing file: ${RELEASE_FILE}

# Create Git Tag
echo Creating Git Tag
git config --global user.email "mswprojectbot@gmail.com"
git config --global user.name "MSW Project Bot"
export GIT_TAG="#$TRAVIS_BUILD_NUMBER"
git tag ${GIT_TAG} -a -m "Tag automatically generated by TravisCI (Build #$TRAVIS_BUILD_NUMBER)"
git push -q https://${OAUTH_KEY}@github.com/${REPO_OWNER}/${REPO} --tags
ls -R

